{% set version = "3.1.3" %}

package:
  name: hydrotrend
  version: {{ version }}

source:
  url: https://github.com/csdms-contrib/hydrotrend/archive/v{{ version }}.tar.gz
  sha256: 13a15bad644f5477e32c64c1adc036be0b279993a4bf2461ac11d5217686a687

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cmake
    - pkg-config
    - bmi-c

test:
  commands:
    - hydrotrend -h
    - hydrotrend -v
    - mkdir HYDRO_IN HYDRO_OUTPUT
    - curl https://raw.githubusercontent.com/csdms-contrib/hydrotrend/master/data/input/HYDRO.IN > ./HYDRO_IN/HYDRO.IN
    - curl https://raw.githubusercontent.com/csdms-contrib/hydrotrend/master/data/input/HYDRO0.HYPS > ./HYDRO_IN/HYDRO0.HYPS
    - hydrotrend

about:
  home: http://csdms.colorado.edu/wiki/Model:HydroTrend
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Climate driven hydrological transport model
  description:
    HydroTrend v3.0 is a climate-driven hydrological water balance
    and transport model that simulates water discharge and sediment
    load at a river outlet.
  doc_url: http://csdms.colorado.edu/wiki/Model:HydroTrend
  dev_url: http://github.com/csdms-contrib/hydrotrend

extra:
  recipe-maintainers:
    - mcflugen
