{% set version = "3.0.6b1" %}

package:
  name: hydrotrend
  version: {{ version }}

source:
  url: https://github.com/csdms-contrib/hydrotrend/archive/v{{ version }}.tar.gz
  sha256: f4e9dba1e6da01fb96c10b013cc98f17104db5bfd9d76ac402e18e1078549135

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

test:
  commands:
    - hydrotrend -h
    - curl https://raw.githubusercontent.com/csdms-contrib/hydrotrend/master/data/input/HYDRO.IN > ./HYDRO.IN
    - curl https://raw.githubusercontent.com/csdms-contrib/hydrotrend/master/data/input/HYDRO0.HYPS > ./HYDRO0.HYPS
    - hydrotrend --prefix=HYDRO --in-dir=. --out-dir=.

about:
  home: http://csdms.colorado.edu/wiki/Model:HydroTrend
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Climate driven hydrological transport model
  description:
    HydroTrend v3.0 is a climate-driven hydrological water balance
    and transport model that simulates water discharge and sediment
    load at a river outlet.
  doc_url: http://csdms.colorado.edu/wiki/Model:HydroTrend
  dev_url: http://github.com/csdms-contrib/hydrotrend

extra:
  recipe-maintainers:
    - mcflugen
