{% set version = "3.0.4" %}

package:
  name: hydrotrend
  version: {{ version }}

source:
  url: https://github.com/csdms-contrib/hydrotrend/archive/v{{ version }}.tar.gz
  sha256: 0893d2669ec69f00a5e2d83b12dc35856ab12230e5deb5f22fd87e42f0f92f33
  patches:
    - var_at_node.patch  # get_var_location should return "node", not "grid"
    - get_var_itemsize.patch  # fix get_var_itemsize not set

build:
  number: 1002
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

test:
  commands:
    - hydrotrend -h
    - curl https://raw.githubusercontent.com/csdms-contrib/hydrotrend/master/data/input/HYDRO.IN > ./HYDRO.IN
    - curl https://raw.githubusercontent.com/csdms-contrib/hydrotrend/master/data/input/HYDRO0.HYPS > ./HYDRO0.HYPS
    - hydrotrend --prefix=HYDRO --in-dir=. --out-dir=.

about:
  home: http://csdms.colorado.edu/wiki/Model:HydroTrend
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Climate driven hydrological transport model
  description:
    HydroTrend v3.0 is a climate-driven hydrological water balance
    and transport model that simulates water discharge and sediment
    load at a river outlet.
  doc_url: http://csdms.colorado.edu/wiki/Model:HydroTrend
  dev_url: http://github.com/csdms-contrib/hydrotrend

extra:
  recipe-maintainers:
    - mcflugen
