appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Zx00HhS7sRCNYfk2OH3WzNrKOHHkZ+kQzL2us4SDTGMezilPQcHsAutdYTjivSCP8+Opxa/c2Mq94g8J0OM+jscpuZeA7TPaTmyhzC5xC1KJbPN6uYg+ssodAJ5ilH3Je5lqTDQD1nEoAL4t8bHagYTM4DWHhTEDwWMbxHenuAiWYXGNrwgrp4NrLbX+28NsKVXrn7YyP/PSTnsTZvLHoVcNq7iYmAYe5mDUz8GQsfCyl7RrPQijFcL7QWe/6Kt0FwJUlctr2abWUsK0JJ/FKsnfwC2apK+7rvG7EQ0mZkn8AJinSElYEPHYrejkHKcuCyc/miokeb/CiVT5HetkevTJF/GwuGEn+akiHdBy5CJpvI2/EH4JWpmxp2vAMmKyZ0oqee9+RfbNE76sjA/Vua1cxUwvbKrrf5ZO5iYmu1DvPwKAZd9jfBzsjevHnr3HT2P47jVuK5P8erFpq7k59yhAM7FdPB0pn0MREEtbWD2aowqTZTdQuMLrdKiNaPElM5O4A3c4Tp90vvQmshIiHVtiw8iKnJ8e3GzZR4xynOzLFMNp17JJWnS5Aa/cB2XddpthFhA3uBF28wchSyC1YSvHDCZuaHM6l49FqXq9N2YDAwTn6Fi+AF9ja6hSYOwHLFvpHrUW1MUz6AR3uvn74l+x43plm9D2an8qkmUGdDM=}
